LIB=	mod_xml_cdr
LIBDIR=	/usr/local/lib/fs_mod

CFLAGS += -I../../../include
CFLAGS += -I/usr/local/include
LDADD += -L/usr/local/lib/ -lcurl

SRCS=	mod_xml_cdr.c

.include "${.CURDIR}/../../fs.mod.mk"
