LIB=	mod_expr
LIBDIR=	/usr/local/lib/fs_mod

CFLAGS += -I../../../include

SRCS=	mod_expr.c expreval.c exprinit.c exprobj.c exprutil.c exprfunc.c \
		exprmem.c exprpars.c exprval.c

.include "${.CURDIR}/../../fs.mod.mk"
