SUBDIR = mod_say_de mod_say_fa mod_say_hr mod_say_ja mod_say_ru \
         mod_say_en mod_say_fr mod_say_hu mod_say_nl mod_say_th \
         mod_say_es mod_say_he mod_say_it mod_say_pt mod_say_zh

.include <bsd.subdir.mk>
